version: '3.9'
services:
  db:
    image: mysql:8.0.33
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot
      MYSQL_ROOT_HOTS: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - people-and-books-network   
  rest-with-spring-boot:
    image: ivojose/rest-with-spring-boot
    restart: always
    build: ./rest_with_spring_boot_and_java
    working_dir: /rest_with_spring_boot_and_java
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - people-and-books-network   
networks:
  people-and-books-network:
    driver: bridge